### ISSUE TITLE
buat algoritma bilangan prima

### ISSUE THREAD

**Issue by huanjian** [huanjian/training#2]
design oke
user oke
dokumen oke

**Comment by huanjian** [comment]
tes aga

**Comment by novian0202** [comment]
https://github.com/huanjian/training/commits/BilanganPrima

**Comment by huanjian** [comment]
@novian0202 anda punya fungsi belum optimal. https://github.com/huanjian/training/commit/d3716d2efc924414dfb3eec12c48aab0b0d7806a#commitcomment-36439682

**Comment by novian0202** [comment]
okey asshiapp
